apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-deployment
  labels:
    app: finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
        - name: accounts
          image:  414178/bist-api:latest
          ports:
            - containerPort: 9081
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  selector:
    app: finance
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9081
      targetPort: 9081